### PR TITLE
cp .gtkrc-2.0 /root

### PR DESCRIPTION
**Pull request by oberon2007**

### CODE REVIEW

**Comment by philmmanjaro** [comment]
I see no issues with this. Do we have any?

**Comment by philmmanjaro** [comment]
**gtk2** is mostly used by **WMs**, however also some **gtk2** based DEs need this. We can remove it, when all adopted **gtk3**

**Comment by oberon2007** [comment]
The problem is also with qt, since qt5ct uses gtk2 settings.

**Comment by philmmanjaro** [comment]
Right. I hope they adopt **gtk3** soon. Anyway, we should keep it until it is fixed.

**Pull request merged**
