### PR TITLE
fix https://bugs.manjaro.org/index.php?do=details&task_id=13

### PR DESCRIPTION
**Pull request by oberon2007**
```
$ ls /bootmnt/manjaro/x86_64/*-image.sqfs
/bootmnt/manjaro/x86_64/i3-image.sqfs    /bootmnt/manjaro/x86_64/mhwd-image.sqfs
/bootmnt/manjaro/x86_64/live-image.sqfs  /bootmnt/manjaro/x86_64/root-image.sqfs
```

### CODE REVIEW

**Comment by oberon2007** [comment]
Or maybe simpler
```
 case $(ls ${img_path}) in
- cinnamon*|deepin*|gnome|i3|lxde|mate|netbook|openbox|pantheon|xfce*)
```
just less specific on the file names ...

**Comment by philmmanjaro** [comment]
@oberon2007: nice catch
@udeved: what about code style? If routines we have like this:
```
if [[ someting ]];then
```
With this change I see most of them now like this:
```
if [[ someting ]]; then
```
See the space before **then**. Do we have there some rules established? Both will work, though ...

**Comment by udeved** [comment]
The conflict is caused, because I removed this function.

Has moved here:
https://github.com/manjaro/desktop-settings/blob/master/shared/skel/.profile

**Comment by udeved** [comment]
Both will work, pointless fiddling with the space.

**Comment by oberon2007** [comment]
abs says this:
>Command separator [semicolon]. Permits putting two or more commands on the same line.
>```
>echo hello; echo there
>
>if [ -x "$filename" ]; then    #  Note the space after the semicolon.
>#+                   ^^
>  echo "File $filename exists."; cp $filename $filename.bak
>else   #                       ^^
>  echo "File $filename not found."; touch $filename
>fi; echo "File test complete."
>```

**Comment by udeved** [comment]
The only question is, is the code broken due to spaces or not?
Lets move on, we need to rebuild settings packages after xfce and kde made transition.
We hopefully end up with on the files in shared/skel, so settings packages may coexist for netinstalls.

**Comment by oberon2007** [comment]
if it doesn't hurt, just keep the whitespaces. now it's at least uniform in this file :wink:

**Comment by udeved** [comment]
Its nonsense to fiddle with it, there is merge conflicts anyway. Lets move on.

**Comment by philmmanjaro** [comment]
@oberon2007: please create a new pull request or rebase your code if this change is still needed ...

**Comment by udeved** [comment]
There is no configure_env() any longer, just to mention it again.

**Comment by philmmanjaro** [comment]
Moving on then ...

**Comment by oberon2007** [comment]
yes. I'll send a new one.

**Comment by udeved** [comment]
This is crazy for whitespaces, but do waste your time if you like.

**Comment by oberon2007** [comment]
not for the whitespaces. what about the qt variables now?

**Comment by oberon2007** [comment]
aha i see. so now just all profiles get it.

**Comment by oberon2007** [comment]
but are you now adding **gt5ct** to shared packages?

**Comment by udeved** [comment]
Read it:

https://wiki.archlinux.org/index.php/environment_variables

**Comment by oberon2007** [comment]
I am talking about the content of the variable.

**Comment by oberon2007** [comment]
It makes no sense if qt5ct is not installed.

**Comment by udeved** [comment]
So what? Then you have a environment variable exported.
Read the wiki.

**Comment by oberon2007** [comment]
So if this is what we do now you'll have to adjust also 16.08 branch or the theming will be broken again. I'll leave it to you guys now. Good night.

**Pull request closed without merging**
