### PR TITLE
my first modfied systemd service

### PR DESCRIPTION
**Pull request by excalibur1234**
this is my first systemd service i have modified. i have looked up all service names and the syntax. i am pretty sure it should work as i want it to work.

maybe @Kirek can take a look at it?

i wanted to modify this service to run after a network connection has been established. it does not matter, if this happens 10 seconds after the system has finished booting. but i do not want to delay the boot process.

### CODE REVIEW

**Comment by Kirek** [comment]
Seems okay, but I don't have much experience writing systemd services.

`-t 30` is definitively wrong, this means a bad mirror would timeout at 30 seconds, not 2s (this is for each mirror, not globally)

If you wanted to do this for the service, you should use `TimeoutSec=`. The default is 90 (in seconds). But note that this may kill before pacman-mirrors it finishes and pacman-mirrors doesnt write anythin till de very end. So I wouldn't recommend using that either.

Maybe `-t 1` is what you want, as it will skip slow mirrors faster.

**Comment by excalibur1234** [comment]
thanks!

now, it should be ready for merge.

**Comment by udeved** [comment]
I'd completely drop the time out thingy.
If a mirror is not available, it will be ranked low anyway.
For our purpose, the fastest mirrors are enough, perhaps even restrict it to the fastest 3 mirrors?

**Comment by Kirek** [comment]
The timeout is the time that pacman-mirrors waits for a mirror to answer and decide if its available or not... the default is 2s, this will only lower it to 1s.

**Comment by udeved** [comment]
Yep, but do we need that? We want fastest responding servers anyway.

**Comment by excalibur1234** [comment]
i do not care so much, whether the timeout is 1 or 2s. i have removed the timeout now.

but something i have just noticed now: do we need the "-g" flag?
(so command becomes "pacman-mirrors -g -m rank --geoip")
or is pacman-mirrors always generating a mirrorlist (except for when called with the --no-update flag)?

**Comment by Kirek** [comment]
you don't need the -g flag if you are using other flags

**Comment by fhdk** [comment]
Could I possibly ask you could help me test the pacman-mirrors-dev package. It should be at v4.0.0rc1 by now.

This new version uses the json files from repo.manjaro.org

It has a new **-f/--fastrack [n]** switch and uses status.json to sort the mirrors and then ranks **n** mirrors by response time.

You use it like  `pacman-mirrors -f 5`

**Comment by udeved** [comment]
@fhdk 

I was referring to this feature, but does it work together?

     pacman-mirrors -f 5 --geoip -m rank

**Comment by excalibur1234** [comment]
@udeved:
it looks like it supports all of that: https://github.com/fhdk/pacman-mirrors#features

**Comment by fhdk** [comment]
On Mon, 2017-03-06 at 01:44 -0800, artoo wrote:
> @fhdk 
> 
> I was referring to this feature, but does it work together?
> 
>      pacman-mirrors -f 5 --geoip -m rank
> 
> https://github.com/fhdk @fhdk
> I was referring to this feature, but does it work together?
> pacman-mirrors -f 5 --geoip -m rank

the -f switch overrides --geoip 

It works this way

It fetches - if network is avaliable - repo.manjaro.org/status.json and
sorts so the mirrors which - at runtime - are known as up-to-date is at
the top of the list.

It then starts ranking the mirrors. If a mirror returns error or times
out it gets a  high response time 99.99 and is ignored.

When the n count is reached the ranked mirrors is sorted by response
time and written to /etc/pacman.d/mirrorlist

So You don't necessarily get all the mirrors from your geoip country
but you get uptodate on all branches and responsive

**Comment by fhdk** [comment]
On Mon, 2017-03-06 at 01:44 -0800, artoo wrote:
> @fhdk 
> 
> I was referring to this feature, but does it work together?
> 
>      pacman-mirrors -f 5 --geoip -m rank
> 
> https://github.com/fhdk @fhdk
> I was referring to this feature, but does it work together?
> pacman-mirrors -f 5 --geoip -m rank

The -f switch overrides --geoip - but uses the new status.json to know about a mirrors update status
So it is a combo of updated mirrors and ranking but since it only
It works this way - and only if network is online:

- It fetches - if network is avaliable - repo.manjaro.org/status.json
- sorts so the mirrors which - at runtime - are known as up-to-date are at
the top of the list.
- It then ranks the mirrors based on response time.
- If a mirror returns error or times out it gets a  high response time 99.99 and is ignored.
- When the n count is reached the ranked mirrors is sorted by response time and written to /etc/pacman.d/mirrorlist

So You don't necessarily get all the mirrors from your geoip country but you get uptodate on all branches and responsive too.

**Comment by excalibur1234** [comment]
@fhdk:
so, "pacman-mirrors -f 2" takes the same time to create /etc/pacman.d/mirrorlist as "pacman-mirrors -f 20"?

"pacman-mirrors -f" always ranks ALL mirrors by response time (the same as "pacman-mirrors -g" does) and additionally takes up-to-date mirrors and writes only n mirrors to /etc/pacman.d/mirrorlist?

**Comment by fhdk** [comment]
No -f 2 will be faster than -f 20 since only 2 mirrors are probed vs 20 mirrors

-f 2 writes 2 mirrors to mirrorlist -f 20 writes 20 mirrors - actually since some of the mirrors offers both http and https you will have an entry for each in mirrorlist

The force of this approach is that we know forehand if the mirror is uptodate and thus only have to rank n mirrors from the uptodate listed mirrors

**Comment by excalibur1234** [comment]
thanks for the explanation.
in this case, the name "fasttrack" actually makes sense, because the tracking process really is faster.

**Comment by excalibur1234** [comment]
@udeved, can you merge this when you are satisfied with it?
...i need it in order to build a fully functioning livecd.

**Pull request merged**
