### PR TITLE
OpenRC, i3

### PR DESCRIPTION
**Pull request by aadityabagga**
/tmp not set as tmpfs by default for OpenRC, as it is not beneficial for all systems..
https://en.opensuse.org/openSUSE:Tmp_on_tmpfs#.2Ftmp.2F_on_harddisk_versus_.2Ftmp.2F_on_tmpfs
OpenRC cleans /tmp on boot anyway by default

Add preliminary i3 support (not tested)

### CODE REVIEW

**Comment by aadityabagga** [comment]
@udeved 

Any objection to this commit or i can push it through..

An I have a suggestion with respect to OpenRC packages:
https://forum.manjaro.org/index.php?topic=19621.msg177780#msg177780

**Comment by udeved** [comment]
I am against removing openrc-core depend
The user will be warned several times if he was to replace his init.

The entire point is to have openrc packages depend on openrc-core, other wise user will wonder why some openrc package doesn't work on a systemd system.
I would like to maintain the clear abstraction of openrc layer pulling in openrc-core, and not allowing user to install any openrc stuff on systemd.

As for the tmpfs, I don't have a clear opinion, but I never encountered issues with /tmp on tmpfs, both on arch an gentoo. Gentoo recommend it.
If the change only serves i3, I would reject it, and find a i3 specific sultion of removing the line.

**Comment by aadityabagga** [comment]
For the packages, its your call.

For tmpfs, I am not against it, I use it on my own system, but it may not be suitable for all cases, eg 2gb ram and less, so I recommend not enabling it by default, but adding it as a comment so that users could uncomment and enable if wanted.

**Comment by udeved** [comment]
We could determine system ram and set tmpfs accordingly, by default it uses half RAM size I think if you don't set a size.

I see actually no point printing a recommend to enable, if we also could print a msg how to disable if problems occur.

**Comment by aadityabagga** [comment]
Nope, we are not printing any messages to enable; its just that it will be disabled by default, and the comment is there so that the user can enable it easily.. 

But I leave the choice upto you, if you feel enabling it by default is more sensible, you can close it.

**Comment by udeved** [comment]
tmpfs has advantages, such as makepkg be default created its builddir there.
Its faster on tmpfs and is nice to hardidsk usage.
I recall you said you like hardware conservation? tmpsfs dfeinitely help with this.

As said, I don't have a clear opinion, but in my view, enabling it has more advantages than disadavatages.
Suse point out its only a few problems found on bugtracker.

**Comment by aadityabagga** [comment]
I think you read it wrong somwhere, Suse says that there are only a few bugs with the *existing* setup, ie, /tmp on harddisk.

Only pro they suggest is that using tmpfs /tmp is cleaned at boot, something that OpenRC does already by default (/etc/rc.conf).

I also added a tmpwatch cron.daily that checks for files in /tmp not used in a week and removes them, to keep /tmp tidy if using it on a server.

Since we are just two people, difficult to reach a quorum ;)

**Comment by udeved** [comment]
I just don't think we should disable it without reason because it may cause in certain situation possible something.
If it does somehow produce trouble, we would get reports.
I opt to keep it enabled and have it properly tested before we disable it for no reason.

**Pull request closed without merging**
